name: Test (Reusable)

on:
  workflow_call:
    inputs:
      cache-version:
        description: Increment to force cache recreation
        type: number
        default: 1
      container-image:
        description: Docker image to run the job in (e.g. elixir:1.18 or membraneframeworklabs/docker_membrane:latest)
        type: string
        default: membraneframeworklabs/docker_membrane:latest

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    container:
      image: ${{ inputs.container-image }}
    steps:
      - uses: actions/checkout@v4

      - name: Elixir executor setup
        uses: ./actions/elixir-executor-setup

      - name: Ensure priv dir exists
        run: mkdir -p priv

      - name: Get mix dependencies
        uses: ./actions/get-mix-deps
        with:
          cache-version: ${{ inputs.cache-version }}

      - name: Restore build cache
        uses: ./actions/use-build-cache
        with:
          cache-version: ${{ inputs.cache-version }}
          env: test

      - name: Compile dependencies
        run: mix deps.compile

      - name: Run tests
        run: mix test --warnings-as-errors
