name: Test (Reusable)

on:
  workflow_call:
    inputs:
      cache-version:
        description: Increment to force cache recreation
        type: number
        default: 1
      executor:
        description: Docker executor to use - 'docker_membrane' or 'elixir'
        type: string
        default: docker_membrane
      executor-version:
        description: Docker image tag for the chosen executor
        type: string
        default: latest

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    container:
      image: >-
        ${{ inputs.executor == 'elixir'
            && format('elixir:{0}', inputs.executor-version)
            || format('membraneframeworklabs/docker_membrane:{0}', inputs.executor-version) }}
    steps:
      - uses: actions/checkout@v4

      - name: Elixir executor setup
        if: inputs.executor == 'elixir'
        uses: ./actions/elixir-executor-setup

      - name: Ensure priv dir exists
        run: mkdir -p priv

      - name: Get mix dependencies
        uses: ./actions/get-mix-deps
        with:
          cache-version: ${{ inputs.cache-version }}

      - name: Restore build cache
        uses: ./actions/use-build-cache
        with:
          cache-version: ${{ inputs.cache-version }}
          env: test

      - name: Compile dependencies
        run: mix deps.compile

      - name: Run tests
        run: mix test --warnings-as-errors
